name: flutter_gpt
description: A simple ChatGPT client

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.5

  cupertino_icons: ^1.0.2
  english_words: ^4.0.0
  provider: ^6.0.0

  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - .env
  uses-material-design: true